image: wagnerstephan/bitbucket-git-ftp

pipelines:
  branches:
    develop:
      - step:
          script:
            - git ftp push --auto-init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.69.152.135/web/dev.mirrorshop.com.ua/public_html
    master:
      - step:
          script:
            - git ftp push --auto-init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.69.152.135/web/demo.mirrorshop.com.ua/public_html
      - step:
          trigger: manual
          script:
            - git ftp push --auto-init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://185.69.152.135/web/mirrorshop.com.ua/public_html
